# Generated by Django 5.2.17 on 2026-08-21 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("imoveis", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("telefone", models.CharField(max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("mensagem", models.TextField(blank=True)),
                ("atendido", models.BooleanField(default=False)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "imovel_relacionado",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="leads",
                        to="imoveis.imovel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contato / Lead",
                "verbose_name_plural": "Contatos / Leads",
                "ordering": ["-criado_em"],
            },
        ),
    ]
