# Generated by Django 5.2.17 on 2026-08-21 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PerfilCorretora",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=120)),
                ("foto", models.ImageField(blank=True, null=True, upload_to="perfil/")),
                (
                    "creci",
                    models.CharField(help_text="Ex: CRECI-PE 12345", max_length=20),
                ),
                ("bio", models.TextField(blank=True)),
                (
                    "regiao_atuacao",
                    models.CharField(
                        help_text="Ex: Recife, Boa Viagem, Casa Forte e região",
                        max_length=200,
                    ),
                ),
                (
                    "whatsapp",
                    models.CharField(
                        help_text="Formato internacional, ex: 5581999999999",
                        max_length=20,
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("instagram_url", models.URLField(blank=True)),
                ("facebook_url", models.URLField(blank=True)),
                ("endereco_escritorio", models.CharField(blank=True, max_length=200)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Perfil da corretora",
                "verbose_name_plural": "Perfil da corretora",
            },
        ),
    ]
