# Generated by Django 5.2.17 on 2026-08-30 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilcorretora',
            name='creci',
            field=models.CharField(help_text='Apenas o número do registro, ex: PE 12345 (o site já mostra o rótulo "CRECI -" na frente).', max_length=20),
        ),
    ]
