# Generated by Django 5.2.17 on 2026-08-30 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0002_alter_perfilcorretora_creci'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilcorretora',
            name='whatsapp',
            field=models.CharField(help_text='Formato internacional, ex: 5581999999999 (funciona mesmo se digitar com espaço, + ou traço — só os números é que contam).', max_length=20),
        ),
    ]
