# Generated by Django 5.2.17 on 2026-08-21 15:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("imoveis", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Depoimento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_cliente", models.CharField(max_length=100)),
                (
                    "email_cliente",
                    models.EmailField(
                        blank=True,
                        help_text="Não é exibido publicamente.",
                        max_length=254,
                    ),
                ),
                ("texto", models.TextField()),
                (
                    "nota",
                    models.PositiveSmallIntegerField(
                        help_text="De 1 a 5 estrelas.",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "aprovado",
                    models.BooleanField(
                        default=False,
                        help_text="Só aparece no site depois de aprovado.",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "imovel_relacionado",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="depoimentos",
                        to="imoveis.imovel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Depoimento",
                "verbose_name_plural": "Depoimentos",
                "ordering": ["-criado_em"],
            },
        ),
    ]
