# Generated by Django 5.2.17 on 2026-08-21 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Imovel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=120)),
                ("slug", models.SlugField(blank=True, max_length=140, unique=True)),
                (
                    "codigo_referencia",
                    models.CharField(
                        blank=True,
                        help_text="Gerado automaticamente (ex: CM-0001) se deixado em branco.",
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("descricao", models.TextField(blank=True)),
                (
                    "tipo_negocio",
                    models.CharField(
                        choices=[
                            ("venda", "Venda"),
                            ("aluguel", "Aluguel"),
                            ("venda_aluguel", "Venda ou Aluguel"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "tipo_imovel",
                    models.CharField(
                        choices=[
                            ("apartamento", "Apartamento"),
                            ("casa", "Casa"),
                            ("casa_condominio", "Casa em Condomínio"),
                            ("terreno", "Terreno / Lote"),
                            ("comercial", "Sala / Ponto Comercial"),
                            ("rural", "Chácara / Sítio / Fazenda"),
                            ("cobertura", "Cobertura"),
                            ("outro", "Outro"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("disponivel", "Disponível"),
                            ("reservado", "Reservado"),
                            ("vendido", "Vendido"),
                            ("alugado", "Alugado"),
                            ("inativo", "Inativo (rascunho)"),
                        ],
                        default="disponivel",
                        max_length=20,
                    ),
                ),
                ("valor", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "valor_condominio",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "valor_iptu",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "area_construida",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="m²",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "area_terreno",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="m²",
                        max_digits=8,
                        null=True,
                    ),
                ),
                ("quartos", models.PositiveSmallIntegerField(default=0)),
                ("suites", models.PositiveSmallIntegerField(default=0)),
                ("banheiros", models.PositiveSmallIntegerField(default=0)),
                ("vagas_garagem", models.PositiveSmallIntegerField(default=0)),
                ("cidade", models.CharField(max_length=80)),
                ("bairro", models.CharField(max_length=80)),
                ("endereco", models.CharField(blank=True, max_length=200)),
                ("cep", models.CharField(blank=True, max_length=9)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "destaque",
                    models.BooleanField(
                        default=False,
                        help_text="Aparece em posição de destaque na vitrine.",
                    ),
                ),
                ("video_url", models.URLField(blank=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Imóvel",
                "verbose_name_plural": "Imóveis",
                "ordering": ["-destaque", "-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="ImovelFoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("imagem", models.ImageField(upload_to="imoveis/%Y/%m/")),
                ("legenda", models.CharField(blank=True, max_length=120)),
                ("ordem", models.PositiveSmallIntegerField(default=0)),
                (
                    "imovel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fotos",
                        to="imoveis.imovel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Foto do imóvel",
                "verbose_name_plural": "Fotos do imóvel",
                "ordering": ["ordem", "id"],
            },
        ),
        migrations.CreateModel(
            name="Realizacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titulo",
                    models.CharField(
                        help_text="Ex: 'Mais uma chave entregue no Boa Viagem!'",
                        max_length=120,
                    ),
                ),
                ("texto", models.TextField(blank=True)),
                ("foto", models.ImageField(upload_to="realizacoes/%Y/%m/")),
                ("publicado_em", models.DateTimeField(auto_now_add=True)),
                ("visivel", models.BooleanField(default=True)),
                (
                    "imovel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="realizacoes",
                        to="imoveis.imovel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Realização (negócio fechado)",
                "verbose_name_plural": "Realizações (negócios fechados)",
                "ordering": ["-publicado_em"],
            },
        ),
    ]
